# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  syntax='proto3',
  serialized_pb=_b('\n\ntest.proto\x12\x04test\")\n\nTestEmails\x12\x1b\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x0b.test.Email\";\n\x05\x45mail\x12\x10\n\x08to_email\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\tb\x06proto3')
)




_TESTEMAILS = _descriptor.Descriptor(
  name='TestEmails',
  full_name='test.TestEmails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emails', full_name='test.TestEmails.emails', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=61,
)


_EMAIL = _descriptor.Descriptor(
  name='Email',
  full_name='test.Email',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to_email', full_name='test.Email.to_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject', full_name='test.Email.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='test.Email.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=122,
)

_TESTEMAILS.fields_by_name['emails'].message_type = _EMAIL
DESCRIPTOR.message_types_by_name['TestEmails'] = _TESTEMAILS
DESCRIPTOR.message_types_by_name['Email'] = _EMAIL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestEmails = _reflection.GeneratedProtocolMessageType('TestEmails', (_message.Message,), dict(
  DESCRIPTOR = _TESTEMAILS,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TestEmails)
  ))
_sym_db.RegisterMessage(TestEmails)

Email = _reflection.GeneratedProtocolMessageType('Email', (_message.Message,), dict(
  DESCRIPTOR = _EMAIL,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Email)
  ))
_sym_db.RegisterMessage(Email)


# @@protoc_insertion_point(module_scope)
